/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#2d3137",
        "on-secondary-container": "#9cbfbe",
        "surface-variant": "#31353c",
        "on-error": "#690005",
        "on-primary-container": "#e3fffe",
        "on-tertiary-container": "#fff9f7",
        "tertiary-fixed": "#ffdbcb",
        "on-primary-fixed": "#002020",
        "secondary-container": "#2d4f4e",
        "surface-container-lowest": "#0a0e14",
        "on-surface": "#dfe2eb",
        "on-tertiary": "#552000",
        "outline-variant": "#3e4949",
        "on-secondary": "#133635",
        "surface-container-high": "#262a31",
        "on-secondary-fixed": "#002020",
        "secondary-fixed-dim": "#aacdcc",
        "on-error-container": "#ffdad6",
        "primary-container": "#008080",
        "surface": "#10141a",
        "on-background": "#dfe2eb",
        "tertiary-container": "#a96039",
        "background": "#10141a",
        "surface-container-highest": "#31353c",
        "primary-fixed-dim": "#76d6d5",
        "outline": "#879392",
        "surface-dim": "#10141a",
        "error": "#ffb4ab",
        "primary": "#76d6d5",
        "tertiary": "#ffb692",
        "on-primary-fixed-variant": "#004f4f",
        "inverse-primary": "#006a6a",
        "primary-fixed": "#93f2f2",
        "tertiary-fixed-dim": "#ffb692",
        "on-tertiary-fixed-variant": "#733512",
        "surface-bright": "#353940",
        "secondary-fixed": "#c5e9e9",
        "secondary": "#aacdcc",
        "error-container": "#93000a",
        "surface-container": "#1c2026",
        "on-surface-variant": "#bdc9c8",
        "inverse-surface": "#dfe2eb",
        "on-primary": "#003737",
        "on-tertiary-fixed": "#341100",
        "surface-tint": "#76d6d5",
        "surface-container-low": "#181c22",
        "on-secondary-fixed-variant": "#2b4c4c"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
